server:
  port: 1402

spring:
  application:
    name: service-user
  mvc:
    # 解决Spring Boot 2.6.X swagger接口列表不显示的问题 这是因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:28999
        namespace: apidoc-swagger-samples
        group: DEV_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: yaml
        namespace: apidoc-swagger-samples
        group: DEV_GROUP
  main:
    allow-bean-definition-overriding: true

knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: root
    password: root
  setting:
    # 是否不显示Knife4j默认的footer，默认为true(显示)
    enableFooter: false
    # 是否自定义Footer，默认为false(非自定义)
    enableFooterCustom: true
    # 自定义Footer内容,支持Markdown语法
    footerCustomContent: Copyright  2022-[apidoc-swagger-samples](https://gitee.com/apidoc-swagger-samples)
  documents: # 文档配置，可配置多个分组
    - group: userApi
      name: 接口说明文档
      locations: classpath:markdown/*
